"""ApplyPilot export — turn Anitalmid career-map results into ApplyPilot config.

Anitalmid identifies good-fit roles (ranked, with titles + strong keywords).
ApplyPilot (a separate AGPL-3.0 CLI) consumes two config files to run its
autonomous job-application pipeline:

    ~/.applypilot/searches.yaml   — search queries (tiered) + locations + boards
    ~/.applypilot/profile.json    — personal profile + target role + skills

This module only GENERATES those two files from Anitalmid's analysis output.
It never imports or embeds ApplyPilot code — the two projects stay separate
(which also keeps Anitalmid's license clean of AGPL copyleft obligations).
"""

from __future__ import annotations

import json
import zipfile
from io import BytesIO
from typing import Any


# How many top roles become search queries, by tier.
TIER_BREAKS = (5, 15, 25)  # 1-5 = tier 1, 6-15 = tier 2, 16-25 = tier 3
MAX_KEYWORD_QUERIES = 10
MAX_PROFILE_SKILLS = 30


def _ranked(top_matches: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Return matches sorted by composite score, highest first."""
    return sorted(top_matches, key=lambda r: float(r.get("composite_score") or 0), reverse=True)


def _title(r: dict[str, Any]) -> str:
    return str(r.get("title") or "").strip()


def _keywords(r: dict[str, Any]) -> list[str]:
    raw = r.get("keywords_strong") or []
    return [str(k).strip() for k in raw if str(k).strip()]


def build_searches_yaml(top_matches: list[dict[str, Any]], location: str = "") -> str:
    """Generate ApplyPilot's searches.yaml from the ranked role matches.

    Role titles become tiered search queries (tier 1 = strongest fits). The top
    matches' strong keywords are appended as tier-3 "broad net" queries.
    """
    ranked = _ranked(top_matches)
    titles = [_title(r) for r in ranked if _title(r)]

    queries: list[tuple[str, int]] = []
    for i, t in enumerate(titles[: TIER_BREAKS[2]]):
        tier = 1 if i < TIER_BREAKS[0] else (2 if i < TIER_BREAKS[1] else 3)
        queries.append((t, tier))

    # High-signal keywords from the top matches as a broader tier-3 net.
    title_lower = {t.lower() for t in titles}
    seen: set[str] = set()
    kw: list[str] = []
    for r in ranked[:10]:
        for k in _keywords(r):
            if k.lower() not in seen and k.lower() not in title_lower:
                seen.add(k.lower())
                kw.append(k)
    for k in kw[:MAX_KEYWORD_QUERIES]:
        queries.append((k, 3))

    remote = (not location) or str(location).strip().lower() in (
        "", "remote", "anywhere", "nationwide", "remote, usa", "usa (remote)",
    )

    lines = [
        "# ApplyPilot search configuration",
        "# Generated by The Anitalmid Project from your career-map analysis.",
        "# Good-fit role titles are tiered by match strength (1 = strongest).",
        "",
        "queries:",
    ]
    for q, tier in queries:
        lines.append(f'  - query: "{q}"')
        lines.append(f"    tier: {tier}")

    lines.append("")
    lines.append("locations:")
    if remote:
        lines.append('  - location: "Remote"')
        lines.append("    remote: true")
    else:
        lines.append(f'  - location: "{str(location).strip()}"')
        lines.append("    remote: false")

    lines += [
        "",
        'country: "USA"',
        "",
        "boards:",
        "  - indeed",
        "  - linkedin",
        "  - glassdoor",
        "  - zip_recruiter",
        "  - google",
        "",
        "defaults:",
        "  results_per_site: 100",
        "  hours_old: 72",
        "",
        "exclude_titles:",
        '  - "intern"',
        '  - "internship"',
        '  - "co-op"',
        '  - "principal"',
        '  - "director"',
    ]
    return "\n".join(lines) + "\n"


def build_profile_json(top_matches: list[dict[str, Any]]) -> str:
    """Generate a partial ApplyPilot profile.json.

    Pre-fills the target role (top match) and a skills seed (strong keywords
    from the top roles). Personal/contact/compensation fields are left blank so
    the user completes them via `applypilot init` (or edits this file directly).
    """
    ranked = _ranked(top_matches)
    target_role = _title(ranked[0]) if ranked else ""

    skills: list[str] = []
    seen: set[str] = set()
    for r in ranked[:5]:
        for k in _keywords(r):
            if k.lower() not in seen:
                seen.add(k.lower())
                skills.append(k)
    skills = skills[:MAX_PROFILE_SKILLS]

    profile = {
        "personal": {
            "full_name": "",
            "preferred_name": "",
            "email": "",
            "password": "",
            "phone": "",
            "address": "",
            "city": "",
            "province_state": "",
            "country": "",
            "postal_code": "",
            "linkedin_url": "",
            "github_url": "",
            "portfolio_url": "",
            "website_url": "",
        },
        "work_authorization": {
            "legally_authorized_to_work": "Yes",
            "require_sponsorship": "No",
            "work_permit_type": "",
        },
        "availability": {
            "earliest_start_date": "Immediately",
            "available_for_full_time": "Yes",
            "available_for_contract": "No",
        },
        "compensation": {
            "salary_expectation": "",
            "salary_currency": "USD",
            "salary_range_min": "",
            "salary_range_max": "",
            "currency_conversion_note": "",
        },
        "experience": {
            "years_of_experience_total": "",
            "education_level": "",
            "current_job_title": "",
            "current_company": "",
            "target_role": target_role,
        },
        "skills_boundary": {
            "languages": [],
            "frameworks": [],
            "devops": [],
            "databases": [],
            "tools": skills,
        },
        "resume_facts": {
            "preserved_companies": [],
            "preserved_projects": [],
            "preserved_school": "",
            "real_metrics": [],
        },
        "eeo_voluntary": {
            "gender": "Decline to self-identify",
            "race_ethnicity": "Decline to self-identify",
            "veteran_status": "I am not a protected veteran",
            "disability_status": "I do not wish to answer",
        },
    }
    return json.dumps(profile, indent=2, ensure_ascii=False) + "\n"


def build_applypilot_zip(top_matches: list[dict[str, Any]], location: str = "") -> bytes:
    """Build a ZIP archive containing searches.yaml + profile.json."""
    searches = build_searches_yaml(top_matches, location)
    profile = build_profile_json(top_matches)

    buf = BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("searches.yaml", searches)
        zf.writestr("profile.json", profile)
    return buf.getvalue()
