services:
  - type: web
    name: anitalmid
    runtime: docker
    rootDir: webapp
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: ANITALMID_SECRET
        generateValue: true
      - key: ANITALMID_BASE_URL
        value: https://theanitalmidproject.com
